/**
 * @file ISchema.ts
 * @description Defines the core structural contract for the MetaUI engine.
 * The schema maps perfectly to the JSON payload generated by the ABAP RTTI extractor.
 */

/**
 * Supported data primitive types that drive plugin selection.
 */
export type FieldType = "string" | "number" | "boolean" | "date" | "dropdown";

/**
 * Value help structure mapping SAP Key/Text pairs.
 */
export interface IValueHelp {
    /** The technical key passed back to the backend. */
    key: string;
    /** The localized descriptive text displayed to the user. */
    text: string;
}

/**
 * Metadata definition for a single atomic input field.
 */
export interface IFieldMetadata {
    /** The technical field name mapping to the data model property. */
    fieldName: string;
    /** The primitive type determining the rendering plugin. */
    type: FieldType;
    /** The localized label text for the UI. */
    label: string;
    /** Indicates if the field is a primary key (often rendered first or highlighted). */
    isKey: boolean;
    /** If true, the field is rendered as a non-editable display element. */
    isReadOnly: boolean;
    /** If true, triggers UI5 validation to ensure a value exists. */
    isRequired: boolean;
    /** Maximum allowed character length for string-based inputs. */
    maxLength?: number;
    /** The total number of significant digits for numeric inputs. */
    precision?: number;
    /** The number of decimal places for numeric inputs. */
    scale?: number;
    /** Pre-loaded static value help arrays for dropdowns. */
    valueHelp?: IValueHelp[];
}

/**
 * Metadata definition for a tabular structure.
 */
export interface ITableMetadata {
    /** The internal ID/name of the table. */
    tableName: string;
    /** The localized table header label. */
    label: string;
    /** Array of field definitions dictating the table's columns. */
    fields: IFieldMetadata[];
}

/**
 * The master schema contract ingested by the Engine to build the UI5 layout.
 */
export interface ISchema {
    /** Determines the root container layout strategy. */
    mode: "form" | "table" | "mixed";
    /** The fields to be rendered at the root level (typically form inputs). */
    rootFields: IFieldMetadata[];
    /** The table structures to be rendered sequentially. */
    tables: ITableMetadata[];
}
